### ISSUE TITLE
stat fails for existing directory

### ISSUE THREAD

**Issue by srerickson** [jszwec/s3fs#3]
I believe I've identified a bug that causes `Stat()` to fail in certain circumstances. Given two objects, `a/b.txt` and `a.txt`, a call to `fs.Stat(fsys, "a")` will fail: `open a: file does not exist`. I believe this is because the `MaxKeys` budget (of 1) in the call to `ListObjects` is used-up by `a.txt` in the response `Contents` ([link](https://github.com/jszwec/s3fs/blob/7531ca5ef00e8e86b1d3063ead609ffe2176db6b/fs.go#L149)).

I'll submit a failing test in a PR

**Comment by jszwec** [comment]
Nice catch thanks!

Fixed by: #4

**Comment by srerickson** [comment]
thanks for the quick review and release!
